---
  kind: pipeline
  type: docker
  name: default

  steps:
  - name: test
    image: node:16.16.0
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    volumes:
    - name: cache
      path: /coverage
    commands:
      - yarn
      - yarn build
      - yarn test

  - name: build-upload-npm
    image: node:16.16.0
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - npm set registry https://registry.npmjs.org/
      - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - yarn semantic-release
    when:
      branch:
      - main
      event:
      - push

  volumes:
  - name: cache
    temp: {}

